language: cpp

compiler: gcc

os: linux
dist: bionic

env: CXX=g++-9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-9-dev
      - g++-9
      
before_install:
  - wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
  - sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-bionic.list http://packages.lunarg.com/vulkan/lunarg-vulkan-bionic.list
  - sudo apt update
  - sudo apt install vulkan-sdk python3-pip python3-setuptools libgl1-mesa-dev xorg-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-xinerama0-dev
  - python3 -m pip install wheel
  - python3 -m pip install conan
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default


script:
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  - mkdir build
  - cd build
  - cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DCMAKE_BUILD_TYPE=Debug
  - make VERBOSE=1