language: cpp

compiler: gcc

os: linux
dist: xenial

env: CXX=g++-8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-8-dev
      - g++-8
      
before_install:
  - wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
  - sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-xenial.list http://packages.lunarg.com/vulkan/lunarg-vulkan-xenial.list
  - sudo apt update
  - sudo apt install vulkan-sdk libxinerama-dev libxcursor-dev libxi-dev libfreetype-dev

script:
  - mkdir build
  - cd build
  - cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python3.5
  - make VERBOSE=1