language: cpp

compiler: gcc

os: linux
dist: bionic

env: CXX=g++-9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-9-dev
      - g++-9
      
before_install:
  - wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
  - sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-bionic.list http://packages.lunarg.com/vulkan/lunarg-vulkan-bionic.list
  - sudo apt update
  - sudo apt install vulkan-sdk python3-pip python3-setuptools
  - python3 -m pip install wheel
  - python3 -m pip install conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan


script:
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  - mkdir build
  - cd build
  - conan install .. --build=missing --profile ../conanProfileTravis
  - cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python3.6
  - make VERBOSE=1