name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        buildType: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
  
    - name: Add Vulkan SDK package
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-bionic.list http://packages.lunarg.com/vulkan/lunarg-vulkan-bionic.list
      
    - name: apt update
      run: sudo apt update
    
    - name: Install wheel from pip
      run: python3 -m pip install wheel 
      
    - name: Install conan from pip
      run: python3 -m pip install conan 
      
    - name: Create default conan profile
      run: conan profile new default --detect --force
      
    - name: Set conan to use C++11 ABI
      run: conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: System dependencies
      run: sudo apt install vulkan-sdk \
                            ninja-build \
                            python3-setuptools \
                            python3-venv \
                            libgl1-mesa-dev \
                            xorg-dev \
                            libxcb-render-util0-dev \
                            libxcb-xkb-dev \
                            libxcb-icccm4-dev \
                            libxcb-image0-dev \
                            libxcb-keysyms1-dev \
                            libxcb-xinerama0-dev
  
    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.buildType}}
      
    - name: Build
      run: |
        cd ${{github.workspace}}/build
        ninja 

      
