name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        buildType: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
  
    - name: Add Vulkan SDK package
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-bionic.list http://packages.lunarg.com/vulkan/lunarg-vulkan-bionic.list
        sudo apt-get update
    
    - name: Install wheel from pip
      run: |
        python3 -m pip install wheel 
        python3 -m pip install conan 
      
    - name: Create default conan profile
      run: |
        conan profile new default --detect --force
        conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Install system dependencies
      run: sudo apt-get install vulkan-sdk ninja-build python3-setuptools python3-venv libgl1-mesa-dev xorg-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-xinerama0-dev
  
    - name: Configure CMake
      run: |
        export CC=gcc-11
        export CXX=g++-11
        cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.buildType}}
      
    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build

      
